/* CHATS ACTIONS TYPES */
export const CHATS_FETCH_SUCCESS = 'CHATS_FETCH_SUCCESS'

export const USER_REGISTER_INIT = 'USER_REGISTER_INIT'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

export const USER_LOGIN_INIT = 'USER_LOGIN_INIT'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

export const AUTH_ON_INIT = 'AUTH_ON_INIT'
export const AUTH_ON_SUCCESS = 'AUTH_ON_SUCCESS'
export const AUTH_ON_ERROR = 'AUTH_ON_ERROR'

export const APP_IS_ONLINE = 'APP_IS_ONLINE';
export const APP_IS_OFFLINE = 'APP_IS_OFFLINE';
