/* CHATS ACTIONS TYPES */
export const CHATS_FETCH_SUCCESS = 'CHATS_FETCH_SUCCESS'
export const CHATS_FETCH_INIT = ' CHATS_FETCH_INIT'
export const CHATS_FETCH_RESTART = ' CHATS_FETCH_RESTART'

export const CHATS_CREATE_SUCCESS = 'CHATS_CREATE_SUCCESS'

export const CHATS_JOIN_SUCCESS = 'CHATS_JOIN_SUCCESS'

export const CHATS_SET_ACTIVE_CHAT = 'CHATS_SET_ACTIVE_CHAT'

export const CHATS_UPDATE_USER_STATE = 'CHATS_UPDATE_USER_STATE'

export const CHATS_MESSAGE_SENT = 'CHATS_MESSAGE_SENT'
export const CHATS_SET_MESSAGES = 'CHATS_SET_MESSAGES'

export const CHATS_REGISTER_MESSAGE_SUB = 'CHATS_REGISTER_MESSAGE_SUB'

/* AUTH ACTIONS TYPES */
export const USER_REGISTER_INIT = 'USER_REGISTER_INIT'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

export const USER_LOGIN_INIT = 'USER_LOGIN_INIT'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

export const AUTH_ON_INIT = 'AUTH_ON_INIT'
export const AUTH_ON_SUCCESS = 'AUTH_ON_SUCCESS'
export const AUTH_ON_ERROR = 'AUTH_ON_ERROR'

export const APP_IS_ONLINE = 'APP_IS_ONLINE';
export const APP_IS_OFFLINE = 'APP_IS_OFFLINE';

/* CONNECTION ACTION TYPES */
export const CONNECTION_USER_STATUS_CHANGED = 'CONNECTION_USER_STATUS_CHANGED';
