/* CHATS ACTIONS TYPES */
export const CHATS_FETCH_SUCCESS = 'CHATS_FETCH_SUCCESS'

export const USER_REGISTER = 'USER_REGISTER'
export const USER_REGISTER_INIT = 'USER_REGISTER_INIT'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

export const USER_LOGIN = ''
export const USER_LOGIN_INIT = 'USER_LOGIN_INIT'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

export const AUTH_ON = 'AUTH_ON'
export const AUTH_ON_INIT = 'AUTH_ON_INIT'
export const AUTH_ON_SUCCESS = 'AUTH_ON_SUCCESS'
export const AUTH_ON_ERROR = 'AUTH_ON_ERROR'